from pathlib import Path
import pprint

#datasetlabel的編號，但居然非oneshot vector

# for app identification
PREFIX_TO_APP_ID = {
    # AIM chat
    "aim_chat_3a": 0,
    "aim_chat_3b": 0,
    "aimchat1": 0,
    "aimchat2": 0,
    'aim_chat': 0,
    'aimchat': 0,
    # Email
    "email1a": 1,
    "email1b": 1,
    "email2a": 1,
    "email2b": 1,
    'email_imap_filetransfer': 1,
    'workstation_thunderbird_imap': 1,
    'workstation_thunderbird_pop': 1,
    'pop_filetransfer': 1,
    # Facebook
    "facebook_audio1a": 2,
    "facebook_audio1b": 2,
    "facebook_audio2a": 2,
    "facebook_audio2b": 2,
    "facebook_audio3": 2,
    "facebook_audio4": 2,
    "facebook_chat_4a": 2,
    "facebook_chat_4b": 2,
    "facebook_video1a": 2,
    "facebook_video1b": 2,
    "facebook_video2a": 2,
    "facebook_video2b": 2,
    "facebookchat1": 2,
    "facebookchat2": 2,
    "facebookchat3": 2,
    'facebook_audio': 2,
    'facebook_chat': 2,
    'facebook_voice_workstation': 2,
    'facebookchat': 2,
    # FTPS
    "ftps_down_1a": 3,
    "ftps_down_1b": 3,
    "ftps_up_2a": 3,
    "ftps_up_2b": 3,
    'ftp_filetransfer': 3,
    # Gmail
    "gmailchat1": 4,
    "gmailchat2": 4,
    "gmailchat3": 4,
    # Hangouts
    "hangout_chat_4b": 5,
    "hangouts_audio1a": 5,
    "hangouts_audio1b": 5,
    "hangouts_audio2a": 5,
    "hangouts_audio2b": 5,
    "hangouts_audio3": 5,
    "hangouts_audio4": 5,
    "hangouts_chat_4a": 5,
    "hangouts_video1b": 5,
    "hangouts_video2a": 5,
    "hangouts_video2b": 5,
    'hangout_audio': 5,
    'hangout_chat': 5,
    'hangouts_voice_workstation': 5,
    'hangoutschat': 5,
    # ICQ
    "icq_chat_3a": 6,
    "icq_chat_3b": 6,
    "icqchat1": 6,
    "icqchat2": 6,
    'icq_chat': 6,
    'icqchat': 6,
    # Netflix
    "netflix1": 7,
    "netflix2": 7,
    "netflix3": 7,
    "netflix4": 7,
    # SCP
    "scp1": 8,
    "scpdown1": 8,
    "scpdown2": 8,
    "scpdown3": 8,
    "scpdown4": 8,
    "scpdown5": 8,
    "scpdown6": 8,
    "scpup1": 8,
    "scpup2": 8,
    "scpup3": 8,
    "scpup5": 8,
    "scpup6": 8,
    # SFTP
    "sftp1": 9,
    "sftp_down_3a": 9,
    "sftp_down_3b": 9,
    "sftp_up_2a": 9,
    "sftp_up_2b": 9,
    "sftpdown1": 9,
    "sftpdown2": 9,
    "sftpup1": 9,
    'sftp_filetransfer': 9,
    # Skype
    "skype_audio1a": 10,
    "skype_audio1b": 10,
    "skype_audio2a": 10,
    "skype_audio2b": 10,
    "skype_audio3": 10,
    "skype_audio4": 10,
    "skype_chat1a": 10,
    "skype_chat1b": 10,
    "skype_file1": 10,
    "skype_file2": 10,
    "skype_file3": 10,
    "skype_file4": 10,
    "skype_file5": 10,
    "skype_file6": 10,
    "skype_file7": 10,
    "skype_file8": 10,
    "skype_video1a": 10,
    "skype_video1b": 10,
    "skype_video2a": 10,
    "skype_video2b": 10,
    'skype_audio': 10,
    'skype_chat': 10,
    'skype_transfer': 10,
    'skype_voice_workstation': 10,
    'skypechat': 10,
    # Spotify
    "spotify1": 11,
    "spotify2": 11,
    "spotify3": 11,
    "spotify4": 11,
    'spotify': 11,
    'spotify2': 11,
    'spotify2-1': 11,
    'spotify2-2': 11,
    'spotifyandrew': 11,
    # Vimeo
    "vimeo1": 12,
    "vimeo2": 12,
    "vimeo3": 12,
    "vimeo4": 12,
    'vimeo_workstation': 12,
    # Voipbuster
    "voipbuster1b": 13,
    "voipbuster2b": 13,
    "voipbuster3b": 13,
    "voipbuster_4a": 13,
    "voipbuster_4b": 13,
    # Youtube
    "youtube1": 14,
    "youtube2": 14,
    "youtube3": 14,
    "youtube4": 14,
    "youtube5": 14,
    "youtube6": 14,
    "youtubehtml5_1": 14,
    'youtube_flash_workstation': 14,
    'youtube_html5_workstation': 14,
    #browsing
    'ssl': 12,
    'ssl_browsing': 12,
    'browsing': 12,
    'browsing2': 12,
    'browsing2-1': 12,
    'browsing2-2': 12,
    'browsing_ara': 12,
    'browsing_ara2': 12,
    'browsing_ger': 12,

    # p2p
    'torrent01': 13,
    'p2p_multiplespeed': 13,
    'p2p_multiplespeed2-1': 13,
    'p2p_vuze': 13,
    'p2p_vuze2-1': 13,
    'pop_filetransfer': 13,
    # Tor
    'torfacebook': 16,
    'torgoogle': 16,
    'tortwitter': 16,
    'torvimeo1': 16,
    'torvimeo2': 16,
    'torvimeo3': 16,
    'toryoutube1': 16,
    'toryoutube2': 16,
    'toryoutube3': 16,

    #vpn
    'vpn_aim_chat1a': 0,
    'vpn_aim_chat1b': 0,
    'vpn_email2a': 1,
    'vpn_email2b': 1,
    'vpn_facebook_chat1a': 2,
    'vpn_facebook_chat1b': 2,
    'vpn_facebook_audio2': 2,
    'vpn_ftps_a': 3,
    'vpn_ftps_b': 3,
    'vpn_hangouts_chat1a': 5,
    'vpn_hangouts_chat1b': 5,
    'vpn_hangouts_audio1': 5,
    'vpn_hangouts_audio2': 5,
    'vpn_icq_chat1a': 6,
    'vpn_icq_chat1b': 6,
    'vpn_netflix_a': 7,
    'vpn_sftp_a': 9,
    'vpn_sftp_b': 9,
    'vpn_skype_chat1a': 10,
    'vpn_skype_chat1b': 10,
    'vpn_skype_files1a': 10,
    'vpn_skype_files1b': 10,
    'vpn_skype_audio1': 10,
    'vpn_skype_audio2': 10,
    'vpn_spotify_a':11,
    'vpn_vimeo_a': 12,
    'vpn_vimeo_b': 12,         
    'vpn_voipbuster1a':13,
    'vpn_voipbuster1b':13,
    'vpn_youtube_a': 14,
    'vpn_bittorrent': 15, 


}

ID_TO_APP = {
    0: "AIM Chat",
    1: "Email",
    2: "Facebook",
    3: "FTPS",
    4: "Gmail",
    5: "Hangouts",
    6: "ICQ",
    7: "Netflix",
    8: "SCP",
    9: "SFTP",
    10: "Skype",
    11: "Spotify",
    12: "Vimeo",
    13: "Voipbuster",
    14: "Youtube",
    15: 'Torrent',
    16: 'Tor',
}

# for traffic identification
PREFIX_TO_TRAFFIC_ID = {
    # Chat
    'aim_chat_3a': 0,
    'aim_chat_3b': 0,
    'aimchat1': 0,
    'aimchat2': 0,
    'facebook_chat_4a': 0,
    'facebook_chat_4b': 0,
    'facebookchat1': 0,
    'facebookchat2': 0,
    'facebookchat3': 0,
    'gmailchat1': 0,
    'gmailchat2': 0,
    'gmailchat3': 0,
    'hangout_chat_4b': 0,
    'hangouts_chat_4a': 0,
    'icq_chat_3a': 0,
    'icq_chat_3b': 0,
    'icqchat1': 0,
    'icqchat2': 0,
    'skype_chat1a': 0,
    'skype_chat1b': 0,

    'aim_chat': 0,
    'aimchat': 0,
    'facebook_chat': 0,
    'facebookchat': 0,
    'hangout_chat': 0,
    'hangoutschat': 0,
    'icq_chat': 0,
    'icqchat': 0,
    'skype_chat': 0,
    'skypechat': 0,
    # Email
    'email1a': 1,
    'email1b': 1,
    'email2a': 1,
    'email2b': 1,

    'email_imap_filetransfer': 1,
    'pop_filetransfer': 1,
    'workstation_thunderbird_imap': 1,
    'workstation_thunderbird_pop': 1,
    # File Transfer
    'ftps_down_1a': 2,
    'ftps_down_1b': 2,
    'ftps_up_2a': 2,
    'ftps_up_2b': 2,
    'scp1': 2,
    'scpdown1': 2,
    'scpdown2': 2,
    'scpdown3': 2,
    'scpdown4': 2,
    'scpdown5': 2,
    'scpdown6': 2,
    'scpup1': 2,
    'scpup2': 2,
    'scpup3': 2,
    'scpup5': 2,
    'scpup6': 2,
    'sftp1': 2,
    'sftp_down_3a': 2,
    'sftp_down_3b': 2,
    'sftp_up_2a': 2,
    'sftp_up_2b': 2,
    'sftpdown1': 2,
    'sftpdown2': 2,
    'sftpup1': 2,
    'skype_file1': 2,
    'skype_file2': 2,
    'skype_file3': 2,
    'skype_file4': 2,
    'skype_file5': 2,
    'skype_file6': 2,
    'skype_file7': 2,
    'skype_file8': 2,

    'ftp_filetransfer': 2,
    'sftp_filetransfer': 2,
    'skype_transfer': 2,
    # Streaming
    'netflix1': 3,
    'netflix2': 3,
    'netflix3': 3,
    'netflix4': 3,
    'vimeo1': 3,
    'vimeo2': 3,
    'vimeo3': 3,
    'vimeo4': 3,
    'youtube1': 3,
    'youtube2': 3,
    'youtube3': 3,
    'youtube4': 3,
    'youtube5': 3,
    'youtube6': 3,
    'youtubehtml5_1': 3,
    'facebook_video1a': 3,
    'facebook_video1b': 3,
    'facebook_video2a': 3,
    'facebook_video2b': 3,
    'hangouts_video1b': 3,
    'hangouts_video2a': 3,
    'hangouts_video2b': 3,
    'skype_video1a': 3,
    'skype_video1b': 3,
    'skype_video2a': 3,
    'skype_video2b': 3,

    'vimeo_workstation': 3,
    'youtube_flash_workstation': 3,
    'youtube_html5_workstation': 3,
    # VoIP
    'facebook_audio1a': 4,
    'facebook_audio1b': 4,
    'facebook_audio2a': 4,
    'facebook_audio2b': 4,
    'facebook_audio3': 4,
    'facebook_audio4': 4,
    'hangouts_audio1a': 4,
    'hangouts_audio1b': 4,
    'hangouts_audio2a': 4,
    'hangouts_audio2b': 4,
    'hangouts_audio3': 4,
    'hangouts_audio4': 4,
    'skype_audio1a': 4,
    'skype_audio1b': 4,
    'skype_audio2a': 4,
    'skype_audio2b': 4,
    'skype_audio3': 4,
    'skype_audio4': 4,
    'spotify1': 4,
    'spotify2': 4,
    'spotify3': 4,
    'spotify4': 4,
    'voipbuster1b': 4,
    'voipbuster2b': 4,
    'voipbuster3b': 4,
    'voipbuster_4a': 4,
    'voipbuster_4b': 4,

    'facebook_audio': 4,
    'facebook_voice_workstation': 4,
    'hangout_audio': 4,
    'hangouts_voice_workstation': 4,
    'skype_audio': 4,
    'skype_voice_workstation': 4,
    'spotify': 4,
    'spotify2': 4,
    'spotify2-1': 4,
    'spotify2-2': 4,
    'spotifyandrew': 4,
    # p2p
    'torrent01': 5,

    'p2p_multiplespeed': 5,
    'p2p_multiplespeed2-1': 5,
    'p2p_vuze': 5,
    'p2p_vuze2-1': 5,
    # browsing
    'torfacebook': 6,
    'torgoogle': 6,
    'tortwitter': 6,
    'torvimeo1': 6,
    'torvimeo2': 6,
    'torvimeo3': 6,
    'toryoutube1': 6,
    'toryoutube2': 6,
    'toryoutube3': 6,
    
    'browsing': 6,
    'browsing2': 6,    
    'browsing2-1': 6,
    'browsing2-2': 6,
    'browsing_ara': 6,
    'browsing_ara2': 6,
    'browsing_ger': 6,
    'ssl': 6,
    'ssl_browsing': 6,

    # VPN: Chat
    'vpn_aim_chat1a': 0,
    'vpn_aim_chat1b': 0,
    'vpn_facebook_chat1a': 0,
    'vpn_facebook_chat1b': 0,
    'vpn_hangouts_chat1a': 0,
    'vpn_hangouts_chat1b': 0,
    'vpn_icq_chat1a': 0,
    'vpn_icq_chat1b': 0,
    'vpn_skype_chat1a': 0,
    'vpn_skype_chat1b': 0,
    # VPN: File Transfer
    'vpn_ftps_a': 1,
    'vpn_ftps_b': 1,
    'vpn_sftp_a': 1,
    'vpn_sftp_b': 1,
    'vpn_skype_files1a': 1,
    'vpn_skype_files1b': 1,
    # VPN: Email
    'vpn_email2a': 2,
    'vpn_email2b': 2,
    # VPN: Streaming
    'vpn_vimeo_a': 3,
    'vpn_vimeo_b': 3,
    'vpn_youtube_a': 3,
    'vpn_netflix_a':3,
    # VPN VoIP
    'vpn_facebook_audio2': 4,
    'vpn_hangouts_audio1': 4,
    'vpn_hangouts_audio2': 4,
    'vpn_skype_audio1': 4,
    'vpn_skype_audio2': 4,
    'vpn_voipbuster1a':4,
    'vpn_voipbuster1b':4,
    'vpn_spotify_a':4,    
    # VPN: Torrent
    'vpn_bittorrent': 5,
}

ID_TO_TRAFFIC = {
    0: 'Chat',
    1: 'Email',
    2: 'File Transfer',
    3: 'Streaming',
    4: 'Voip',
    5: 'P2P',
    6: 'browsing',
}

dir_checklist={}
source="./dataset/completePCAP/"
data_dir_path = Path(source)
for pcap_path in sorted(data_dir_path.iterdir()):
    pcap_path=str(pcap_path)
    if pcap_path[-1*len('.pcap'):] == '.pcap' :
        dir_checklist[pcap_path[len(source)-2:-1*len('.pcap')].lower()]=0        
    elif pcap_path[-1*len('.pcapng'):] == '.pcapng' :
        dir_checklist[pcap_path[len(source)-2:-1*len('.pcapng')].lower()]=0

#pprint.pprint(dir_checklist)


for k,v in PREFIX_TO_TRAFFIC_ID.items():
    try:
        k=k.lower()
        PREFIX_TO_APP_ID[k]
        PREFIX_TO_TRAFFIC_ID[k]
        dir_checklist[k]
    except:
        print(k)        